name: mqtt_client_repository
description: Dart package which manages the AWS IoT domain.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^9.8.0

flutter:
  assets:
    - assets/certs/AmazonRootCA1.pem