name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  very_good_analysis: ^3.1.0
  amplify_flutter: ^1.0.0-next.7
  amplify_auth_cognito: ^1.0.0-next.7
  amplify_authenticator: ^1.0.0-next.5