name: mqtt_repository
description: Dart package which manages the AWS IoT domain.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  aws_iot_api: ^2.0.0
  mqtt_client: ^9.8.0
  http: ^0.13.5

dev_dependencies:
  very_good_analysis: ^4.0.0+1

flutter: